spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:identifier.sqlite
    username:
    password:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update
